### ISSUE TITLE
チーム　『濃い茶』

### ISSUE THREAD

**Issue by pokohide** [hironomiu-vg/1day-2016-05-29#114]
koicha ブランチで開発。　#117

**Comment by S-Shimotori** [comment]
せっかくなので爽健美茶のものをマージしました。

**Comment by pokohide** [comment]
- [ ] 自分か相手のHPが0になったらゲーム終了 
- [ ] レイアウト整形
- [ ] 結果によってスコアが反映
- [x] じゃんけん結果によってダメージ HP減ったり 👍 
- [x] [画像](https://www.google.co.jp/search?tbm=isch&tbs=rimg%3ACYTY0gJXWRxFIjj8QBC7-cxY8VSX9VmeyIDSbo1nCgasxA3hb1RAVX34pvJFFPhh2c0_1NqNU_1nft9S65BPY0erQhdyoSCfxAELv5zFjxEUl2imUxhj6rKhIJVJf1WZ7IgNIRvOI09eb3JxkqEglujWcKBqzEDREMJN-4RkjuMSoSCeFvVEBVffimEepZN-pSZ0jiKhIJ8kUU-GHZzT8ReQN9R79RHZAqEgk2o1T-d-31LhFIReVeAkkC1CoSCbkE9jR6tCF3Ea3_15lU7FcBR&q=%E4%BC%9D%E8%AA%AC%20%E6%95%B5%20%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88&ved=0ahUKEwia4rKc1v7MAhXJGZQKHWehAqMQ9C8ICQ&dpr=1&biw=1440&bih=805)を白抜きでimagesに入れる 🔢
- [ ] ゲーム終了時にランキングをデータベースに保存
- [x] HPのプログレスバーをパーセントによって色を変える
- [x] ダメージを与える時に超かっこいいエフェクト

担当者
👍  はpokohide
🔢  はS-Shimotori
💯  は。。。
